VAGRANT_API_VERSION = "2"

Vagrant.configure("2") do |config|
#  config.vm.define :teste do |config|
#  config.vm.define :ubunto.teste do |config|  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubunto.teste"
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 80,  host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.provider "VM" do |vm|
     vm.memory = "1024"
     vm.cpus = "1"
  end

end
