# Versão da API do Vagrant
VAGRANT_API_VERSION = "2"

# Configuração principal do Vagrant
Vagrant.configure(VAGRANT_API_VERSION) do |config|

  # Configuração da máquina virtual
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu.teste"

  # Configuração de rede
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"

  # Configuração do provider (VirtualBox neste caso)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # 1GB de memória
    vb.cpus = 1         # 1 CPU
  end

  # Configurações adicionais
  # config.vm.provision "shell", inline: "apt-get update"

end
