
Vagrant.configure("2") do |config|

#  config.vm.define :teste do |config|
  
  config.vm.box = "ubuntu/trusty64"
#  config.vm.define :ubunto.teste do |config|
  config.vm.hostname = "ubunto.teste"
  config.vm.provider "VM" do |vm|
    vm.memory = "1024"
    vm.cpus = "1"
  end

end
